### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by devxan** [YOYITsM3M8/YOYITsM3M8#1]
@retronbv JSYK I currently can't access discord because I don't have a phone number to verify that I'm a real human. 😞

**Comment by retronbv** [comment]
> @retronbv JSYK I currently can't access discord because I don't have a phone number to verify that I'm a real human. 😞

JSYK?

**Comment by devxan** [comment]
> > @retronbv JSYK I currently can't access discord because I don't have a phone number to verify that I'm a real human. 😞
> 
> JSYK?

*Just So You Know **:p**

**Comment by retronbv** [comment]
Use that free sms service thingy

**Comment by devxan** [comment]
@retronbv 
> Use that free SMS service thingy

Yeah, Discord recognizes that the phone numbers being used on many of those sites aren't real human phone numbers. I am waiting on my mother to verify my Discord account using her phone.

**Comment by retronbv** [comment]
When you get your disc back spam dm me

**Comment by devxan** [comment]
> @retronbv When you get your disc back spam dm me

I currently have 75 pings. I can't view a single message yet, but - 
### **I will ping you.** 

_Update:_ Now 77 messages!
Then I had 66, then 311, then 0 🙂
